apple_resource(
    name = 'AppResources',
    dirs = [],
    files = glob(['BuckExample/*.png','BuckExample/*.xib','BuckExample/*.storyboard']),
)

apple_binary(
    name = 'AppBinary',
    srcs = glob([
        '*.swift',
      ]),
    frameworks = [
        '$SDKROOT/System/Library/Frameworks/Foundation.framework',
        '$SDKROOT/System/Library/Frameworks/UIKit.framework',
        '$SDKROOT/System/Library/Frameworks/SwiftUI.framework'
    ],
)

apple_bundle(
    name = 'App',
    binary = ':AppBinary',
    extension = 'app',
    info_plist = 'Info.plist',
    info_plist_substitutions = {
        'PRODUCT_BUNDLE_IDENTIFIER': 'vitor.BuckExample',
        'CURRENT_PROJECT_VERSION': '1',
    },
)